### ISSUE TITLE
File -> New

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#18]
Menu button File -> New does nothing, maybe should clear the console

**Comment by tmhglnd** [comment]
Good idea. I at first let it do nothing since I don't want to add an extra editor for example. But clearing the editor might be a good idea, although also potentially confusing for those who expect an extra window to be opened.

**Comment by GuillemGongora** [comment]
Opening a new console is indeed an interesting idea, but also I find myself wanting to clear the whole console to try out new things. Maybe another option could be added to do so.

**Comment by tmhglnd** [comment]
This is now included as an option under `File > Clear All Code`. When clicking it gives you a pop-up window asking "Are you sure?". Since the editor has no history you will lose all the code typed if you answer the pop-up window with `y` or `yes`.
