### ISSUE TITLE
"Speed" argument in samples does nothing

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#20]
Pretty self explanatory:
`new sample clap_909 name(clap) g(1)
         set clap time(1/2) speed(1)`
and
`new sample clap_909 name(clap) g(1)
         set clap time(1/2) speed(2)`
sound exactly the same.

**Comment by tmhglnd** [comment]
Yes! I noticed this bug lately as well. Will work on it!

**Comment by tmhglnd** [comment]
This should be fixed now! As for now the `note()` method in sample is temporarily disabled untill I've found a better way to combine the `speed()` and `note()` methods in the sample. Also fixed the a bug with `offset()`, where the offset doesn't have any effect when the sample is playing in reverse.
