### ISSUE TITLE
Simple math operations to rings

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#21]
I was wondering if it's possible to perform simple math operations to existing rings.
For example I have:
`ring pattern (0 1 2 4)`
and I thought it would be useful to generate other rings from this one, like (multiplying by 0.25):
`ring probabilities (0 0.25 0.5 1)`

**Comment by wooloogooloo** [comment]
Yes, id also like this!

**Comment by tmhglnd** [comment]
Yes! I like that as well, will work on this. Will probably result in something that looks like:
```java
ring pattern [0 1 2 4]
ring probabilities multiply(pattern 0.25)
//=> [0 0.25 0.5 1]
```
OR
```java
ring pattern [0 1 2 4]
ring probabilities divide(pattern 4)
//=> [0 0.25 0.5 1]
```

Maybe with optional abbreviation
```java
ring pattern [0 1 2 4]
ring probabilities mul(pattern 0.25)
//=> [0 0.25 0.5 1]
```

**Comment by GuillemGongora** [comment]
Following this, also the option of rounding up floats:
`ring floats randomFloat(4 0 1)` -> [0.2 0.4 0.7 0.9]
to:
`ring rounded round(floats)` -> [0 0 1 1]

**Comment by tmhglnd** [comment]
Will include this as well! 

But as an alternative to for your example you could also just use:
```java
ring beat random(4 2)
//=> [0 1 0 0 1 1 1 0]
```
In the future there will also be a coin-toss method called `coin` which does the same but only needs one argument for the amount of values returned in the array:
```java
ring beat coin(8)
//=> [0 1 0 0 1 1 1 0]
```

**Comment by tmhglnd** [comment]
Basic arithmetic methods are now added: `add()`, `subtract() | sub()`, `multiply() | mul()` and `divide() | div()`, 

```java
ring r [0 3 7]
ring r2 add(r 12)
//=> [12 15 19]

ring r7 [0 3 7]
ring r8 subtract(r7 3.5)
//=> [-3.5 0.5 3.5]

ring r3 [0 1 2 4]
ring r4 divide(r3 4)
//=> [0 0.25 0.5 1]

ring r5 [0 2 4 8 10]
ring r6 multiply(r5 0.1)
//=> [0 0.2 0.4 0.8 1]
```
Also works with second arrays as input, in this case the first array determines the output length, the second array will be repeated for the length of the first.

```java
ring r0 [0 1 2 3 4]
ring r1 [1 3]
ring r2 add(r0 r1)
//=> [1 4 3 6 5]
//=> because: 0+1, 1+3, 2+1, 3+3, 4+1
```
