### ISSUE TITLE
Ring every() accepting floats

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#23]
I was wondering if `ring every()` could accept floats (or fractions) to have rings played other than every full bars.

**Comment by tmhglnd** [comment]
Good idea! Will surely be possible

**Comment by tmhglnd** [comment]
This is now possible (or was already possible...? Not sure) since all ring methods moved to the NodeJS total-serialism package. Here is how it works:

```
every(<ring> <bars> <division> <offset>)

bars (multiply by division) : default = 4
division (length of 1 bar)  : default = 16 
offset (in bars)            : default = 0
```

The resulting output length is `bars * division`

```js
ring rtm [1 0 0 1 1]

// default note division is 16
ring barRtm every(rtm 1)
//=> [1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0]
```

```js
ring rtm [1 0 0 1 1]

// default note division is 16
ring barRtm every(rtm 1.5 8 0.5)
//=> [0 0 0 0 1 0 0 1 1 0 0 0]
```
