### ISSUE TITLE
Code after set [name] does not evaluate

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#25]
In
`new sample snare_909 name(snr) g(1)`
`set snr time(1/2)`
the code after `set` doesn't evaluate. Either it is a `name()` recognition problem or a `set` problem.
`new sample snare_909 name(snr) g(1) time(1/2)`
does work.

**Comment by tmhglnd** [comment]
Fixed, this was a bug in the parser where leading whitespace resulted in an incorrect parse.
This previously didn't work:
```java
new sample snare_909 name(snr) g(1)
    set snr time(1/2)
```
Now it should be fine.
