### ISSUE TITLE
Automatically log code

### ISSUE THREAD

**Issue by tmhglnd** [tmhglnd/mercury#27]
Add an option to automatically store the current code everytime the code gets executed. This can be stored under `~/Documents/Mercury/logs` for example.

**Comment by GuillemGongora** [comment]
Oh, that's super nice for keeping track of the changes!!
Thank you!!

**Comment by tmhglnd** [comment]
Sadly it's not yet implemented, but i'm working on it!

**Comment by tmhglnd** [comment]
This is now included in the latest commit. There are 2 ways to turn on the Auto Logging:

1. Click the toggle `Auto Log Code` in the main mercury window
2. Run the code `autoLog 1` in the mercury code editor

The setting is also automatically stored in the preferences.

The logs are stored under: `/Users/<username>/Documents/Mercury/Code Logs/`(same on mac and windows)

Also added the recording feature that stores the files to `/Users/<username>/Documents/Mercury/Recordings/`
