### ISSUE TITLE
Text overflowing in 1920x1080 Win10

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#29]
The text in the console overflows at the bottom and doesn't properly adjust when reaching more than 23 lines in 1920x1080 resolution (Win10). It seems to be a problem with the different screen ratios setup (also doesn't work in other ratios except 4:3). Specially annoying when working in fullscreen where the ratio cannot be adjusted manually.

**Comment by tmhglnd** [comment]
I noticed this a couple days ago as well, will have to see what I can do about it! I believe it also has to do with the selected font.

**Comment by tmhglnd** [comment]
This is now fixed in commit 55960230e598008ab86432b03001048b1a2c1760 by adding a setting for `line spacing` under the `Settings > Visual Settings`. With this parameter you can change the distance between lines to make sure line 30 fits in the screen.
