### ISSUE TITLE
History not finding the aproppiate path

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#30]
`jit.textfile: ~/Desktop//mercuryHistory/mrcry_2020.05.04_15.35.22.txt: error -1 creating file`
Pretty self explanatory. I guess it's still in development :)

**Comment by tmhglnd** [comment]
Did you pull the latest version of Mercury? Because in the latest version the file should be stored under: `/Users/<username>/Documents/Mercury/Code Logs` and the filename should look like: `sketch_2020.05.05_12.14.16.txt`

**Comment by GuillemGongora** [comment]
Works perfectly with the latest version
