### ISSUE TITLE
Error on git clone Win10

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#34]
I get the following error when cloning:
```
error: invalid path 'mercury_ide_0.9.9/patchers/>=p.maxpat'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```
I think it's due to the use of `>` as explained here: https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file
Downloading as `.zip` and extracting works just fine

**Comment by tmhglnd** [comment]
Removed `>=p.maxpat` from the project and is replaced with `gtep.maxpat`

**Comment by GuillemGongora** [comment]
Perfect! Working now!
