### ISSUE TITLE
Shift modifier not working properly Win10

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#41]
Shift modifiers to access characters above numbers don't work anymore (i.e: `(` is reported as `9`). It seems to be due to a switch from taking the input from ASCII values in `quickKey.maxpat`.
Sticking to ASCII values might also solve the issue with area specific keyboard layouts (my `[` is accessed through a `AltGr` modifier key in the spanish keyboard layout, but still reporting `91` as the ASCII value).

**Comment by tmhglnd** [comment]
Okay, good to know! I thought I fixed the issues by changing all this, but appearantly i made it worse for Windows. I'll probably roll back and rethink this again.

**Comment by tmhglnd** [comment]
Should be fixed in 6ff23ba3c9cff252dc945ea2d231dd02c59ba691
