### ISSUE TITLE
Fibonacci ring method outputting characters

### ISSUE THREAD

**Issue by oscarvanleest** [tmhglnd/mercury#51]
It seems that when using the Fibonacci ring method the ring gets filled with characters instead of integers. 
A look into the variables shows this as well. the note function doesn't take these as valid data

**Comment by tmhglnd** [comment]
Correct, this is a bug that still needs fixing indeed.

**Comment by tmhglnd** [comment]
This is fixed in 651a73c605055f966b568e661095d2db635fe836. The `fibonacci()` function now outputs the values as Numbers, bare in mind that if the value exceeds the maximum 64-bit floating-point it will not return correct values anymore. This will occur after the 78th fibonacci number.
