### ISSUE TITLE
Parameter setting using OSC-in

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#56]
Setting parameters using OSC-in locks the source of the value to always OSC-in even when deleting the OSC path and assigning a new fixed value.
For example:
`new synth sine note(/OSC/input1 3)`
always gets the value from `/OSC/input1` even when replacing and running new code
`new synth sine note(0 3)`

**Comment by tmhglnd** [comment]
Will investigate soon!

**Comment by tmhglnd** [comment]
Let me know if this fixes the bug, haven't had time to test it!

**Comment by GuillemGongora** [comment]
Fixes the bug but doesn't allow for a constant stream of OSC values anymore, only one change after evaluating

**Comment by tmhglnd** [comment]
Okay, this needs a bit more attention then haha!

**Comment by tmhglnd** [comment]
Okay, now it should be fixed! Only when changing from an argument (like a `ring`) to an OSC message it will preserve the ring as long as it has not received any message from the OSC yet. Not sure if this is wanted or that it should reset to default first, but I think this might be the nicest way that doesn't give unwanted results during a performance.
