### ISSUE TITLE
Only display cmd floating window

### ISSUE THREAD

**Issue by GuillemGongora** [tmhglnd/mercury#9]
Be able to hide the audio and rendering screen if needed leaving only the cmd in a floating window (useful for when checking other windows in the background, like the documentation).

**Comment by tmhglnd** [comment]
Will have to look into this. I believe at the moment minimizing the main window will also minimize the floating-window since it is part of the same application.

**Comment by GuillemGongora** [comment]
Exactly! Very minor thing, though

**Comment by tmhglnd** [comment]
Solution to this issue is:
Turn off `Always in Front` under `Settings > Visual Setup`
